apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tybooks-ingress
  namespace: tybooks
spec:
  rules:
    - host: tybooks.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tybooks-app
                port:
                  number: 8080
